name: Reusable Java Maven Workflow

on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version to install'
        required: false
        type: string
        default: '17'
      MAVEN_GOALS:
        description: 'Maven goals to execute'
        required: false
        type: string
        default: 'clean package'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK ${{ inputs.JAVA_VERSION }}
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: ${{ inputs.JAVA_VERSION }}
          cache: 'maven'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Build JAR File
        run: mvn ${{ inputs.MAVEN_GOALS }}
